// src/app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Map filters", // You might want a more general title for the app
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Add dark mode base classes to the body */}
      <body className={`${inter.className} bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-200`}>
        {children}
      </body>
    </html>
  );
}